app:
  image: 730011650125.dkr.ecr.ap-southeast-2.amazonaws.com/buildkite-build-status:stable
  environment:
    BUILD_FARM_RUN:
    # Environments from caller
    BUILDBOX_AGENT_UID:
    BUILDBOX_AGENT_GID:
  volumes:
    - .:/application
  working_dir: /application
